FROM klee/klee:latest

USER root

RUN apt-get update && apt-get install -y \
    python3-pip \
    gawk \
    git \
    wget && \
    pip3 install wllvm

ENV LLVM_COMPILER=clang
ENV LLVM_CONFIG=$(which llvm-config)

RUN git clone https://github.com/emmettlsc/coreutils-klee-demo.git /coreutils

# Build Coreutils with gcov (Step 1)
RUN cd /coreutils && \
    mkdir obj-gcov && cd obj-gcov && \
    FORCE_UNSAFE_CONFIGURE=1 ../configure --disable-nls \
    CFLAGS="-g -fprofile-arcs -ftest-coverage" && \
    make -j$(nproc)

# Build Coreutils with LLVM (Step 2)
RUN cd /coreutils && \
    mkdir obj-llvm && cd obj-llvm && \
    CC=wllvm FORCE_UNSAFE_CONFIGURE=1 ../configure --disable-nls \
    CFLAGS="-g -O0 -Xclang -disable-llvm-passes \
    -D__NO_STRING_INLINES -D_FORTIFY_SOURCE=0 -U__OPTIMIZE__" && \
    make -j$(nproc) && \
    cd src && \
    find . -executable -type f -name 'echo' | xargs -I '{}' extract-bc '{}'

# Switch back to the original user for security
USER klee

CMD ["/bin/bash"]
